<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="arm_base_length" value="0.1" />
    <xacro:property name="arm_base_width" value="0.1" />
    <xacro:property name="arm_base_height" value="0.02" />
    <xacro:property name="forearm_length" value="0.3" />
    <xacro:property name="forearm_radius" value="0.02" />
    <xacro:property name="hand_length" value="0.3" />
    <xacro:property name="hand_radius" value="0.02" />

    <link name="arm_base_link">
        <visual>
            <geometry>
                <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}"/>
            </geometry>
            <origin xyz="0 0 ${arm_base_height/2}" rpy="0 0 0"/>
            <material name="orange" /> 
        </visual> 
        <collision>
            <geometry>
                <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}"/>
            </geometry>
            <origin xyz="0 0 ${arm_base_height/2}" rpy="0 0 0"/>
        </collision>
        <xacro:box_inertia m="0.5" l="${arm_base_length}" w="${arm_base_width}" h="${arm_base_height}" xyz="0 0 ${arm_base_height/2}" rpy ="0 0 0"/>  
    </link>

    <link name="forearm_link">
        <visual>
            <geometry>
                <cylinder radius="${forearm_radius}" length="${forearm_length}"/>
            </geometry>
            <origin xyz="0 0 ${forearm_length/2}" rpy="0 0 0"/>
            <material name="yellow" /> 
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${forearm_radius}" length="${forearm_length}"/>
            </geometry>
            <origin xyz="0 0 ${forearm_length/2}" rpy="0 0 0"/>
        </collision>
        <xacro:cylinder_inertia m="0.3" r="${forearm_radius}" h="${forearm_length}" xyz="0 0 ${forearm_length/2}" rpy ="0 0 0"/>        
    </link>

    <link name="hand_link">
        <visual>
            <geometry>
                <cylinder radius="${hand_radius}" length="${hand_length}"/>
            </geometry>
            <origin xyz="0 0 ${hand_length/2}" rpy="0 0 0"/>
            <material name="orange" /> 
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${hand_radius}" length="${hand_length}"/>
            </geometry>
            <origin xyz="0 0 ${hand_length/2}" rpy="0 0 0"/>
        </collision>
        <xacro:cylinder_inertia m="0.3" r="${hand_radius}" h="${hand_length}" xyz="0 0 ${hand_length/2}" rpy ="0 0 0"/>
    </link>

    <joint name="base_to_arm" type="fixed">
        <parent link="base_link"/>
        <child link="arm_base_link"/>
        <origin xyz="${base_length/4} 0 ${base_height}" rpy="0 0 0"/>   
    </joint>

    <joint name="arm_base_to_forearm" type="revolute">
        <parent link="arm_base_link"/>
        <child link="forearm_link"/>
        <origin xyz="0 0 ${arm_base_height}" rpy="0 0 0"/>   
        <axis xyz="0 1 0"/>
        <limit lower="0" upper="${pi/2}" effort="100" velocity="100"/>
        <dynamics friction="0.3" damping="0.3"/>
    </joint>

    <joint name="forearm_to_hand" type="revolute">
        <parent link="forearm_link"/>
        <child link="hand_link"/>
        <origin xyz="0 0 ${forearm_length}" rpy="0 0 0"/>   
        <axis xyz="0 1 0"/>
        <limit lower="0" upper="${pi/2}" effort="100" velocity="100"/>
        <dynamics friction="0.3" damping="0.3"/>
    </joint>

    <gazebo>
        <plugin 
            filename="libignition-gazebo-joint-state-publisher-system.so"
            name="ignition::gazebo::systems::JointStatePublisher">

            <joint_name>arm_base_to_forearm</joint_name>
            <joint_name>forearm_to_hand</joint_name>    

            <topic>joint_states</topic>
        </plugin>
    </gazebo>

    <gazebo>
        <plugin
            filename="libignition-gazebo-joint-position-controller-system.so"
            name="ignition::gazebo::systems::JointPositionController">
            <joint_name>arm_base_to_forearm</joint_name>
            <topic>arm_base_to_forearm_cmd</topic>

            <p_gain>5.0</p_gain>
            <i_gain>0.1</i_gain>
            <d_gain>0.01</d_gain>
        </plugin>
        <plugin
            filename="libignition-gazebo-joint-position-controller-system.so"
            name="ignition::gazebo::systems::JointPositionController"> 
            <joint_name>forearm_to_hand</joint_name>
            <topic>forearm_to_hand_cmd</topic>

            <p_gain>3.0</p_gain>
            <i_gain>0.1</i_gain>
            <d_gain>0.01</d_gain>
        </plugin>
    </gazebo>

</robot>