<?xml version="1.0"?>
<robot name="minimal_robot" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- outer paramters（changing through launch file） -->
  <xacro:arg name="base_height" default="0.2"/>
  <xacro:arg name="sensor_size" default="0.1"/>
  
  <!-- inner paramters -->
  <xacro:property name="base_size" value="0.4"/>
  <xacro:property name="base_height" value="$(arg base_height)"/>
  <xacro:property name="sensor_size"  value="$(arg sensor_size)"/>
  <xacro:property name="sensor_offset_z" value="${base_height/2 + sensor_size/2}"/>
  <xacro:property name="wheel_radius" value="0.1"/>
  <xacro:property name="wheel_width" value="0.05"/>

  <!-- base_footprint-->
  <link name="base_footprint"/>
  
  <joint name="base_footprint_to_base_link" type="fixed">
  <parent link="base_footprint"/>
  <child link="base_link"/>
  <!-- 如果你希望 base_footprint 在 base_link 正下方某个高度，
       可以在这里设置 xyz；目前简化成完全重合 -->
  <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- base_link -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_size} ${base_size} ${base_height}"/>
      </geometry>
      <material name="blue">
        <color rgba="0.1 0.4 0.8 1.0"/>
      </material>
    </visual>
    
    <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${base_size} ${base_size} ${base_height}"/>
        </geometry>
    </collision>
    
    <inertial>
        <mass value="1.0"/> <!-- kg -->
        <inertia
          ixx="0.01" ixy="0.0" ixz="0.0"
          iyy="0.01" iyz="0.0"
          izz="0.02"/>
    </inertial>      
  </link>

  <!-- sensor_link -->
  <link name="sensor_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${sensor_size} ${sensor_size} ${sensor_size}"/>
      </geometry>
      <material name="red">
        <color rgba="0.8 0.1 0.1 1.0"/>
      </material>
    </visual> 
    
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${sensor_size} ${sensor_size} ${sensor_size}"/>
      </geometry>
    </collision> 
    
    <inertial>
      <mass value="0.05"/>
      <inertia
        ixx="0.00005" ixy="0.0" ixz="0.0"
        iyy="0.00005" iyz="0.0"
        izz="0.00005"/>
    </inertial>
  </link>

  <!-- Joint：auto calculate the height of sensor -->
  <joint name="base_to_sensor" type="fixed">
    <parent link="base_link"/>
    <child link="sensor_link"/>
    <origin xyz="0.2 0 ${sensor_offset_z}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>
  
  <!-- left wheel link -->
  <link name="left_wheel_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1.0"/>
      </material>
    </visual>
    
    <collision>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    
    <inertial>
      <mass value="0.2"/>
      <inertia
        ixx="0.0002" ixy="0.0" ixz="0.0"
        iyy="0.0002" iyz="0.0"
        izz="0.0001"/>
    </inertial>
  </link>
  
  <!-- left wheel joint -->
  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel_link"/>
    <origin xyz="0 ${base_size/2} ${-base_height/2 + wheel_radius/2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>
  
  <!-- right wheel link -->
  <link name="right_wheel_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1.0"/>
      </material>
    </visual>
    
    <collision>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    
    <inertial>
      <mass value="0.2"/>
        <inertia
          ixx="0.0002" ixy="0.0" ixz="0.0"
          iyy="0.0002" iyz="0.0"
          izz="0.0001"/>
    </inertial>
  </link>
  
  <!-- right wheel join -->
  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel_link"/>
    <origin xyz="0 ${-base_size/2} ${-base_height/2 + wheel_radius/2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>
  
</robot>

